# Generated by Django 5.0.7 on 2024-08-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0007_alter_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
